
# DAY 1

# NUMPY

In [2]:
import numpy as np
a = [1,2,20,9]
a1 = np.array(a)
print(a1)

[ 1  2 20  9]


In [36]:
import numpy as np
a = [1,2,20,9]
a1 = np.array(a,np.int8)
print(a1)
print(a1.dtype)

[ 1  2 20  9]
int8


In [9]:
a2 = [1,2,3,445566,5,44]
a3 = np.array(a2,np.int8)
print(a3)

[  1   2   3 126   5  44]


In [10]:
a2 = [1,2,3,445566,5,44]
a3 = np.array(a2,np.int32)
print(a3)

[     1      2      3 445566      5     44]


In [11]:
# int function define the storage if we allocate int8 it mean we have allocating 8 byte memorey

# ACCESS SPECIFIC ELEMENT

In [12]:
a = [7,4,3,5,2,3]
a4 = np.array(a)
print(a4[0])

7


In [13]:
print(np.array(a[1]))

4


# ONE D-ARRAY

In [16]:
one_d = [2,1,5,5,3]
d1 = np.array(one_d)
print(d1)

[2 1 5 5 3]


# TWO D-ARRAY

In [17]:
two_d = ([[1,2,3],[4,5,6]])
d2 = np.array(two_d)
print(d2)

[[1 2 3]
 [4 5 6]]


# THREE D-ARRAY

In [18]:
three_d = ([[[1,2],[3,4],[5,6]]])
d3 = np.array(three_d)
print(d3)

[[[1 2]
  [3 4]
  [5 6]]]


# METHOD

# SHAPE

In [25]:
one_d = [2,1,5,5,3]
d1 = np.array(one_d)
print(d1.shape)

(5,)


In [28]:
t = ([[43,4,2],[2,4,3]])
t1 = np.array(t)
print(t1.shape)

(2, 3)


In [32]:
multi_level_array = ([[[[[5,6]]]]])
f = np.array(multi_level_array)
print(f.shape)

(1, 1, 1, 1, 2)


# SIZE

In [29]:
one_d = [2,1,5,5,3]
d1 = np.array(one_d)
print(d1.size)

5


In [31]:
t = ([[43,4,2],[2,4,3]])
t1 = np.array(t)
print(t1.size)

6


In [33]:
multi_level_array = ([[[[[5,6]]]]])
f = np.array(multi_level_array)
print(f.size)

2


# dtype

In [34]:
t = ([[43,4,2],[2,4,3]])
t1 = np.array(t)
print(t1.dtype)

int32


In [35]:
multi_level_array = ([[[[[5,6]]]]])
f = np.array(multi_level_array)
print(f.dtype)

int32


# REPLACING ELEMENT

In [40]:
r = [2,1,2,3,4,5]
r1 = np.array(r)
print(r1)
r1[0]= 0
print(r1)

[2 1 2 3 4 5]
[0 1 2 3 4 5]


In [41]:
t = ([[43,4,2],[2,4,3]])
t1 = np.array(t)
t1[1][0]= 5
print(t1)

[[43  4  2]
 [ 5  4  3]]


# INTRINSIC NUMPY

# ZEROS

In [44]:
z = np.zeros((3,3))
print(z)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [45]:
z1 = np.zeros((4,4))
print(z1)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


# ARANGE

In [51]:
r = np.arange(6)
print(r)

[0 1 2 3 4 5]


In [53]:
r1 = np.arange(2)
print(r1)

[0 1]


# RESHAPE

In [61]:
r2 = [0,1,2,3,4,5]
r3=np.array(r2)
print(r3.reshape(3,2))

[[0 1]
 [2 3]
 [4 5]]


In [63]:
r2 = [0,1,2,3,4,5,6,7,8]
r3=np.array(r2)
print(r3.reshape(3,3))

[[0 1 2]
 [3 4 5]
 [6 7 8]]


# RAVEL

In [70]:
r2 = [0,1,2,3,4,5]
r3=np.array(r2)
print(r3.reshape(3,2))
print(r3.ravel())

[[0 1]
 [2 3]
 [4 5]]
[0 1 2 3 4 5]


# LINSPACE

In [78]:
lspace = np.linspace(1,5,10)
print(lspace)

[1.         1.44444444 1.88888889 2.33333333 2.77777778 3.22222222
 3.66666667 4.11111111 4.55555556 5.        ]


In [9]:
l = np.linspace(2,5,12)
print(l)

[2.         2.27272727 2.54545455 2.81818182 3.09090909 3.36363636
 3.63636364 3.90909091 4.18181818 4.45454545 4.72727273 5.        ]


# EMPTY

In [7]:
import numpy as np
e = np.empty((5,3))
print(e)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


# IDENTITY

In [2]:
import numpy as np
i = np.identity((3))
print(i)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [3]:
i = np.identity(5)
print(i)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


# ONES

In [90]:
o = np.ones((3,3))
print(o)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


# AXIS

In [ ]:
# axis = 0 mean horizental or row
# axis = 1 mean vertical or columns

In [3]:
import numpy as np
x = np.array([[1,2,3],[4,5,6]])
print(x.sum(axis = 0))

[5 7 9]


In [13]:
x = np.array([[1,2,3],[4,5,6]])
x.sum(axis = 0)

array([5, 7, 9])

In [15]:
x = np.array([[1,2,3],[4,5,6]])
x.sum(axis = 1)

array([ 6, 15])

In [18]:
x = np.array([[1,2,3],[4,5,6]])
print(x.ndim)

2


In [19]:
x = np.array([[1,2,3],[4,5,6]], ndmin = 5)
print(x.ndim)

5


In [1]:
import numpy as np
x = np.array([[1,2,3],[4,5,6]])
print(x.nbytes)
print(x.dtype)

24
int32


In [22]:
x1 = np.array([1,3,46,9])
print(x1.argmax())

2


In [24]:
x1 = np.array([1,3,46,9])
print(x1.argmin())

0


In [25]:
x1 = np.array([1,3,46,9])
print(x1.argsort())

[0 1 3 2]


# prove that array is storage efficient then list

In [28]:
import sys
import numpy as np
python_array = [0,4,55,2]
numpy_array = np.array([python_array])
print(sys.getsizeof(1)*len(python_array))
print(sys.getsizeof(1)*len(numpy_array))

112
28


In [36]:
x = np.array([[[1,2],[3,4],[5,6]]])
print(x.argmax())

5


In [37]:
x = np.array([[[1,2],[3,4],[5,6]]])
print(x.argmin())

0


In [38]:
x = np.array([[[1,2],[3,4],[5,6]]])
print(x.argsort())

[[[0 1]
  [0 1]
  [0 1]]]


In [1]:
import numpy as np
x = np.array([[[1,2],[3,4],[5,6]]])
print(x)
print(x.sum(axis = 0))

[[[1 2]
  [3 4]
  [5 6]]]
[[1 2]
 [3 4]
 [5 6]]


In [42]:
x = np.array([[[1,2],[3,4],[5,6]]])
print(x.argmax(axis = 0))

[[0 0]
 [0 0]
 [0 0]]


# DAY 2

# addition

In [2]:
import numpy as np
a1 = np.array([[1,2,3],[4,5,6],[7,1,0]])
a2 = np.array([[1,2,1],[4,0,6],[8,1,0]])
print(a1+a2)

[[ 2  4  4]
 [ 8  5 12]
 [15  2  0]]


# multiplication

In [3]:
import numpy as np
a1 = np.array([[1,2,3],[4,5,6],[7,1,0]])
a2 = np.array([[1,2,1],[4,0,6],[8,1,0]])
print(a1*a2)

[[ 1  4  3]
 [16  0 36]
 [56  1  0]]



# SQRT

In [4]:
s = np.array([4,9,16,36])
print(np.sqrt(s))

[2. 3. 4. 6.]


# SUM

In [4]:
s = np.array([4,9,16,36])
print(s.sum())
print(np.sum(s))
print(np.max(s))
print(np.min(s))

65
65
36
4


# WHERE

In [9]:
a1 = np.array([[1,2,3],[4,5,6],[7,1,0]])
print(np.where(a1>5))

(array([1, 2], dtype=int64), array([2, 0], dtype=int64))


# non zero

In [11]:
a1 = np.array([[1,2,3],[4,5,6],[7,1,0]])
print(a1)
print(np.nonzero(a1))

[[1 2 3]
 [4 5 6]
 [7 1 0]]
(array([0, 0, 0, 1, 1, 1, 2, 2], dtype=int64), array([0, 1, 2, 0, 1, 2, 0, 1], dtype=int64))


# CONCATENATE

In [13]:
# list
a1 = np.array([1,2,3])
a2 = np.array([4,5,6])
print(np.concatenate((a1,a2)))

[1 2 3 4 5 6]


In [21]:
arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([[5,6],[7,8]])
#print(np.concatenate((arr1,arr2)))
print(np.concatenate((arr1,arr2), axis = 0))
print('\r')
print(np.concatenate((arr1,arr2), axis = 1))


[[1 2]
 [3 4]
 [5 6]
 [7 8]]

[[1 2 5 6]
 [3 4 7 8]]


# SLICING

In [23]:
s = np.array([4,9,16,36])
print(s[:])
print(s[0:2])
print(s[1:])

[ 4  9 16 36]
[4 9]
[ 9 16 36]


In [31]:
i = np.array([1,2,3,4,5,6,7,8,9])
print(i[1:5:3])
print(i[1:8:3])
print(i[::2])
print(i[::3])

[2 5]
[2 5 8]
[1 3 5 7 9]
[1 4 7]


# stacking

In [39]:
a1 = np.array([1,2,3])
a2 = np.array([4,5,6])
print(np.stack((a1,a2)))

[[1 2 3]
 [4 5 6]]


In [40]:
a1 = np.array([1,2,3])
a2 = np.array([4,5,6])
print(np.vstack((a1,a2)))

[[1 2 3]
 [4 5 6]]


In [41]:
a1 = np.array([1,2,3])
a2 = np.array([4,5,6])
print(np.hstack((a1,a2)))

[1 2 3 4 5 6]


In [42]:
a1 = np.array([1,2,3])
a2 = np.array([4,5,6])
print(np.dstack((a1,a2)))

[[[1 4]
  [2 5]
  [3 6]]]


In [49]:
a1 = np.array([1,2,3])
a2 = np.array([4,5,6])
print(np.stack((a1,a2),axis=1))

[[1 4]
 [2 5]
 [3 6]]


In [50]:
a1 = np.array([1,2,3])
a2 = np.array([4,5,6])
print(np.stack((a1,a2),axis=0))

[[1 2 3]
 [4 5 6]]


# SPLITING


In [68]:
a1 = np.array([1,2,3])
print(np.array_split(a1,3))

[array([1]), array([2]), array([3])]


In [69]:
a1 = np.array([1,2,3])
print(np.hsplit(a1,3))

[array([1]), array([2]), array([3])]


In [84]:
s = np.array([1,2,3,4,5,6,6,7])
p=(np.array_split(s,3))
print(p)
print(p[1])

[array([1, 2, 3]), array([4, 5, 6]), array([6, 7])]
[4 5 6]


In [81]:
s = np.array([[1,2,3,4,5,6,6,7],[3,4,5,6,7,2,3,5]])
print(np.array_split(s,3,axis = 1))

[array([[1, 2, 3],
       [3, 4, 5]]), array([[4, 5, 6],
       [6, 7, 2]]), array([[6, 7],
       [3, 5]])]


# COPY

In [62]:
a = np.array([1,2,3,4,5])
c = np.copy(a)
print(a)
print(c)

[1 2 3 4 5]
[1 2 3 4 5]


In [64]:
a = np.array([1,2,3,4,5])
c = a.copy()
a[-1] = 10
print(a)
print(c)

[ 1  2  3  4 10]
[1 2 3 4 5]


# view

In [65]:
a = np.array([1,2,3,4,5])
c = a.view()
print(a)
print(c)

[1 2 3 4 5]
[1 2 3 4 5]


In [66]:
a = np.array([1,2,3,4,5])
c = a.view()
a[-1] = 10
print(a)
print(c)

[ 1  2  3  4 10]
[ 1  2  3  4 10]


In [92]:
fill = np.array([71,72,73,75])
fill1 = fill>72
fill2 = fill%2 == 0
new_arr1 = fill[fill1]
new_arr2 = fill[fill2]

print(fill1)
print(fill2)
print(new_arr1)
print(new_arr2)

[False False  True  True]
[False  True False False]
[73 75]
[72]


# FLIP

In [91]:
i = np.array([1,2,3,4,5,6])
print(np.flip(i))

[6 5 4 3 2 1]


# DAY 3

# PANDAS

# DATAFRAME

In [17]:
import numpy as np
import pandas as pd
dict = {
    'name':["ghayur","waseem","abbasi","wafadar"],
    'marks':[975,875,950,875],
    'city':["m garh","dokota","mailsi","m garh"]
}
pdf = pd.DataFrame(dict)
pdf.to_csv("marks data.csv")
print(pdf)

      name  marks    city
0   ghayur    975  m garh
1   waseem    875  dokota
2   abbasi    950  mailsi
3  wafadar    875  m garh


# HEAD

In [12]:
print(pdf.head(2))

     name  marks    city
0  ghayur    975  m garh
1  waseem    875  dokota


In [13]:
print(pdf.head())

      name  marks    city
0   ghayur    975  m garh
1   waseem    875  dokota
2   abbasi    950  mailsi
3  wafadar    875  m garh


# TAIL

In [2]:
import numpy as np
import pandas as pd
dict = {
    'name':["ghayur","waseem","abbasi","wafadar"],
    'marks':[975,875,950,875],
    'city':["m garh","dokota","mailsi","m garh"]
}
pdf = pd.DataFrame(dict)
print(pdf.tail(2))

      name  marks    city
2   abbasi    950  mailsi
3  wafadar    875  m garh


In [3]:
print(pdf.tail())

      name  marks    city
0   ghayur    975  m garh
1   waseem    875  dokota
2   abbasi    950  mailsi
3  wafadar    875  m garh


# DESCRIBE

In [5]:
# it will describe all about numerical data
print(pdf.describe())

           marks
count    4.00000
mean   918.75000
std     51.53882
min    875.00000
25%    875.00000
50%    912.50000
75%    956.25000
max    975.00000


# READ CSV FILE

In [10]:
import pandas as pd
df = pd.read_csv("train.csv")
print(df)


  Train No  Speed      City
0      22U     81    Lahore
1      14D     70   Karachi
2      10D     75    Quetta
3      33U     65  Peshawar


In [14]:
print(df["Speed"])

0    81
1    70
2    75
3    65
Name: Speed, dtype: int64


In [17]:
df["Speed"][1] = 90
print(df)

  Train No  Speed      City
0      22U     81    Lahore
1      14D     90   Karachi
2      10D     75    Quetta
3      33U     65  Peshawar


C:\Users\Administrator\AppData\Local\Temp\ipykernel_3740\3779487539.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Speed"][1] = 90


In [18]:
# it will override the excel indexing
df.to_csv("train2.csv",index=False)
print(df)

  Train No  Speed      City
0      22U     81    Lahore
1      14D     90   Karachi
2      10D     75    Quetta
3      33U     65  Peshawar


# SERIES

In [4]:
import numpy as np
import pandas as pd
sr = pd.Series(np.random.rand(100))
print(sr)

0     0.718857
1     0.627276
2     0.086540
3     0.308797
4     0.795409
        ...   
95    0.077935
96    0.191763
97    0.589845
98    0.511298
99    0.415124
Length: 100, dtype: float64


In [5]:
new_df = pd.DataFrame(np.random.rand(100,5))
print(new_df)

           0         1         2         3         4
0   0.138539  0.670904  0.608348  0.754440  0.745276
1   0.102114  0.970152  0.030832  0.894518  0.528816
2   0.339483  0.975843  0.300823  0.562222  0.895624
3   0.227656  0.906127  0.416459  0.645781  0.501691
4   0.104325  0.423600  0.188278  0.096609  0.218623
..       ...       ...       ...       ...       ...
95  0.116329  0.698458  0.426150  0.552274  0.258438
96  0.166687  0.524580  0.065409  0.043642  0.306076
97  0.463220  0.740360  0.716583  0.968224  0.610061
98  0.740513  0.385430  0.439321  0.773341  0.210739
99  0.767631  0.509351  0.181298  0.442191  0.625717

[100 rows x 5 columns]


In [6]:
new_df = pd.DataFrame(np.random.rand(100,5),index= np.arange(100))
print(new_df)

           0         1         2         3         4
0   0.175308  0.705088  0.762862  0.569843  0.780843
1   0.319452  0.797450  0.026815  0.850854  0.176900
2   0.668731  0.737345  0.205142  0.421783  0.963488
3   0.974965  0.735314  0.932024  0.892929  0.985574
4   0.861701  0.456065  0.215219  0.512216  0.136328
..       ...       ...       ...       ...       ...
95  0.029110  0.485132  0.116373  0.421584  0.420155
96  0.539918  0.169009  0.205321  0.472994  0.668802
97  0.045681  0.797353  0.505919  0.719599  0.014682
98  0.351928  0.522831  0.004508  0.718505  0.423461
99  0.719572  0.643123  0.750068  0.775942  0.774845

[100 rows x 5 columns]


In [25]:
print(new_df.to_string())

           0         1         2         3         4
0   0.211997  0.565431  0.053296  0.672894  0.143203
1   0.711047  0.580650  0.340208  0.667409  0.398879
2   0.639021  0.271338  0.558136  0.725831  0.618024
3   0.568219  0.805542  0.250923  0.622163  0.024855
4   0.426478  0.357677  0.701669  0.284773  0.163024
5   0.705229  0.241928  0.645312  0.345589  0.558754
6   0.761644  0.552253  0.637754  0.084746  0.747250
7   0.728629  0.572719  0.920281  0.930203  0.880984
8   0.713171  0.967418  0.454549  0.511946  0.561629
9   0.133753  0.623412  0.308606  0.711228  0.314419
10  0.562491  0.868200  0.946874  0.479094  0.055882
11  0.818235  0.510150  0.046299  0.960188  0.889173
12  0.052882  0.959600  0.659203  0.142674  0.452512
13  0.603462  0.961894  0.765920  0.046706  0.375471
14  0.961320  0.358681  0.197755  0.720642  0.323486
15  0.304061  0.358128  0.734491  0.090900  0.907949
16  0.767832  0.761794  0.210125  0.273351  0.084859
17  0.154584  0.448940  0.222715  0.065003  0.

In [26]:
print(new_df.head())

          0         1         2         3         4
0  0.211997  0.565431  0.053296  0.672894  0.143203
1  0.711047  0.580650  0.340208  0.667409  0.398879
2  0.639021  0.271338  0.558136  0.725831  0.618024
3  0.568219  0.805542  0.250923  0.622163  0.024855
4  0.426478  0.357677  0.701669  0.284773  0.163024


In [27]:
print(new_df.tail())

           0         1         2         3         4
95  0.328113  0.374273  0.436902  0.671407  0.724995
96  0.677663  0.961481  0.537131  0.665960  0.389119
97  0.060463  0.768446  0.977617  0.315068  0.576758
98  0.584779  0.201941  0.794731  0.265511  0.973375
99  0.680894  0.654969  0.758216  0.049705  0.897447


In [28]:
print(new_df.index)

Int64Index([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
            17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
            34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
            51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
            68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
            85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
           dtype='int64')


In [29]:
print(new_df.to_numpy())

[[2.11996542e-01 5.65431438e-01 5.32956026e-02 6.72893765e-01
  1.43203229e-01]
 [7.11046580e-01 5.80650453e-01 3.40207682e-01 6.67409160e-01
  3.98879120e-01]
 [6.39020728e-01 2.71338418e-01 5.58135549e-01 7.25831334e-01
  6.18023981e-01]
 [5.68218793e-01 8.05541536e-01 2.50923395e-01 6.22162889e-01
  2.48548991e-02]
 [4.26477564e-01 3.57676910e-01 7.01668917e-01 2.84773398e-01
  1.63023861e-01]
 [7.05228553e-01 2.41928147e-01 6.45311574e-01 3.45588512e-01
  5.58754393e-01]
 [7.61644283e-01 5.52253188e-01 6.37753865e-01 8.47458309e-02
  7.47250080e-01]
 [7.28628503e-01 5.72718857e-01 9.20281315e-01 9.30202726e-01
  8.80984279e-01]
 [7.13170530e-01 9.67417501e-01 4.54549400e-01 5.11946060e-01
  5.61628824e-01]
 [1.33753170e-01 6.23411946e-01 3.08606256e-01 7.11228260e-01
  3.14419452e-01]
 [5.62490963e-01 8.68200458e-01 9.46874466e-01 4.79094042e-01
  5.58817912e-02]
 [8.18235072e-01 5.10149685e-01 4.62987546e-02 9.60188282e-01
  8.89172762e-01]
 [5.28819925e-02 9.59600351e-01 6.592034

In [30]:
print(new_df.T)

         0         1         2         3         4         5         6   \
0  0.211997  0.711047  0.639021  0.568219  0.426478  0.705229  0.761644   
1  0.565431  0.580650  0.271338  0.805542  0.357677  0.241928  0.552253   
2  0.053296  0.340208  0.558136  0.250923  0.701669  0.645312  0.637754   
3  0.672894  0.667409  0.725831  0.622163  0.284773  0.345589  0.084746   
4  0.143203  0.398879  0.618024  0.024855  0.163024  0.558754  0.747250   

         7         8         9   ...        90        91        92        93  \
0  0.728629  0.713171  0.133753  ...  0.131815  0.990904  0.728421  0.238231   
1  0.572719  0.967418  0.623412  ...  0.176332  0.086235  0.524477  0.366871   
2  0.920281  0.454549  0.308606  ...  0.069660  0.898928  0.171057  0.191007   
3  0.930203  0.511946  0.711228  ...  0.602598  0.899109  0.965742  0.017231   
4  0.880984  0.561629  0.314419  ...  0.597976  0.131944  0.658974  0.180742   

         94        95        96        97        98        99  
0  0

In [31]:
print(new_df.sort_index(axis=0, ascending = False))

           0         1         2         3         4
99  0.680894  0.654969  0.758216  0.049705  0.897447
98  0.584779  0.201941  0.794731  0.265511  0.973375
97  0.060463  0.768446  0.977617  0.315068  0.576758
96  0.677663  0.961481  0.537131  0.665960  0.389119
95  0.328113  0.374273  0.436902  0.671407  0.724995
..       ...       ...       ...       ...       ...
4   0.426478  0.357677  0.701669  0.284773  0.163024
3   0.568219  0.805542  0.250923  0.622163  0.024855
2   0.639021  0.271338  0.558136  0.725831  0.618024
1   0.711047  0.580650  0.340208  0.667409  0.398879
0   0.211997  0.565431  0.053296  0.672894  0.143203

[100 rows x 5 columns]


In [32]:
view_df = new_df
view_df[0][0]=1234
print(view_df.head())

             0         1         2         3         4
0  1234.000000  0.565431  0.053296  0.672894  0.143203
1     0.711047  0.580650  0.340208  0.667409  0.398879
2     0.639021  0.271338  0.558136  0.725831  0.618024
3     0.568219  0.805542  0.250923  0.622163  0.024855
4     0.426478  0.357677  0.701669  0.284773  0.163024


# VIEW

In [33]:
new_df[0][0]=1234
print(new_df.head())

             0         1         2         3         4
0  1234.000000  0.565431  0.053296  0.672894  0.143203
1     0.711047  0.580650  0.340208  0.667409  0.398879
2     0.639021  0.271338  0.558136  0.725831  0.618024
3     0.568219  0.805542  0.250923  0.622163  0.024855
4     0.426478  0.357677  0.701669  0.284773  0.163024


# copy

In [34]:
copy_df = new_df.copy()
copy_df[0][0]=5678
print(copy_df)

              0         1         2         3         4
0   5678.000000  0.565431  0.053296  0.672894  0.143203
1      0.711047  0.580650  0.340208  0.667409  0.398879
2      0.639021  0.271338  0.558136  0.725831  0.618024
3      0.568219  0.805542  0.250923  0.622163  0.024855
4      0.426478  0.357677  0.701669  0.284773  0.163024
..          ...       ...       ...       ...       ...
95     0.328113  0.374273  0.436902  0.671407  0.724995
96     0.677663  0.961481  0.537131  0.665960  0.389119
97     0.060463  0.768446  0.977617  0.315068  0.576758
98     0.584779  0.201941  0.794731  0.265511  0.973375
99     0.680894  0.654969  0.758216  0.049705  0.897447

[100 rows x 5 columns]


# difference between copy and view

In [35]:
print(view_df.head(3))

             0         1         2         3         4
0  1234.000000  0.565431  0.053296  0.672894  0.143203
1     0.711047  0.580650  0.340208  0.667409  0.398879
2     0.639021  0.271338  0.558136  0.725831  0.618024


In [36]:
print(copy_df.head(3))

             0         1         2         3         4
0  5678.000000  0.565431  0.053296  0.672894  0.143203
1     0.711047  0.580650  0.340208  0.667409  0.398879
2     0.639021  0.271338  0.558136  0.725831  0.618024


# LOC FUNCTION

In [37]:
loc_df = new_df
loc_df.loc[0,0]=4321
print(loc_df.head(3))

             0         1         2         3         4
0  4321.000000  0.565431  0.053296  0.672894  0.143203
1     0.711047  0.580650  0.340208  0.667409  0.398879
2     0.639021  0.271338  0.558136  0.725831  0.618024


In [38]:
new_df.columns=list("ABCDE")
print(new_df.head(3))

             A         B         C         D         E
0  4321.000000  0.565431  0.053296  0.672894  0.143203
1     0.711047  0.580650  0.340208  0.667409  0.398879
2     0.639021  0.271338  0.558136  0.725831  0.618024


# DAY 4

In [50]:
df = pd.DataFrame(np.random.rand(15,5),index = np.arange(15),columns=['A','B','C','D','E'])
print(df)

           A         B         C         D         E
0   0.103812  0.468474  0.859287  0.349166  0.185609
1   0.511680  0.204882  0.263489  0.589505  0.895365
2   0.380236  0.131411  0.945151  0.167400  0.690530
3   0.944711  0.702896  0.546167  0.594436  0.903404
4   0.924199  0.438872  0.904389  0.039238  0.350977
5   0.234998  0.951546  0.521000  0.297437  0.679109
6   0.164734  0.077882  0.465917  0.283837  0.743285
7   0.008583  0.418011  0.576375  0.846319  0.036786
8   0.746561  0.941830  0.427376  0.025858  0.878224
9   0.182624  0.384800  0.508343  0.294174  0.464538
10  0.036670  0.735343  0.047704  0.288377  0.177707
11  0.550370  0.403481  0.694171  0.533740  0.398502
12  0.582828  0.480664  0.807208  0.559791  0.289812
13  0.059456  0.987773  0.725639  0.746979  0.850797
14  0.942013  0.526855  0.158705  0.722046  0.953095


# LOC

In [64]:
print([df['C']<0.3])

[0     False
1      True
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10     True
11    False
12    False
13    False
14     True
Name: C, dtype: bool]


In [65]:
print(df.loc[df["C"]<0.3]) # loc is label based you have to spacify rows and columns

           A         B         C         D         E
1   0.511680  0.204882  0.263489  0.589505  0.895365
10  0.036670  0.735343  0.047704  0.288377  0.177707
14  0.942013  0.526855  0.158705  0.722046  0.953095


In [66]:
print(df.loc[(df["C"]<0.4) & (df["D"]>0.1)])

           A         B         C         D         E
1   0.511680  0.204882  0.263489  0.589505  0.895365
10  0.036670  0.735343  0.047704  0.288377  0.177707
14  0.942013  0.526855  0.158705  0.722046  0.953095


In [67]:
print(df.loc[:,["C","D"]])

           C         D
0   0.859287  0.349166
1   0.263489  0.589505
2   0.945151  0.167400
3   0.546167  0.594436
4   0.904389  0.039238
5   0.521000  0.297437
6   0.465917  0.283837
7   0.576375  0.846319
8   0.427376  0.025858
9   0.508343  0.294174
10  0.047704  0.288377
11  0.694171  0.533740
12  0.807208  0.559791
13  0.725639  0.746979
14  0.158705  0.722046


In [68]:
print(df.loc[[6,8],:])

          A         B         C         D         E
6  0.164734  0.077882  0.465917  0.283837  0.743285
8  0.746561  0.941830  0.427376  0.025858  0.878224


# DROP

In [71]:
print(df.drop(["E"], axis = 1))

           A         B         C         D
0   0.103812  0.468474  0.859287  0.349166
1   0.511680  0.204882  0.263489  0.589505
2   0.380236  0.131411  0.945151  0.167400
3   0.944711  0.702896  0.546167  0.594436
4   0.924199  0.438872  0.904389  0.039238
5   0.234998  0.951546  0.521000  0.297437
6   0.164734  0.077882  0.465917  0.283837
7   0.008583  0.418011  0.576375  0.846319
8   0.746561  0.941830  0.427376  0.025858
9   0.182624  0.384800  0.508343  0.294174
10  0.036670  0.735343  0.047704  0.288377
11  0.550370  0.403481  0.694171  0.533740
12  0.582828  0.480664  0.807208  0.559791
13  0.059456  0.987773  0.725639  0.746979
14  0.942013  0.526855  0.158705  0.722046


In [73]:
print(df.drop([0], axis = 0))

           A         B         C         D         E
1   0.511680  0.204882  0.263489  0.589505  0.895365
2   0.380236  0.131411  0.945151  0.167400  0.690530
3   0.944711  0.702896  0.546167  0.594436  0.903404
4   0.924199  0.438872  0.904389  0.039238  0.350977
5   0.234998  0.951546  0.521000  0.297437  0.679109
6   0.164734  0.077882  0.465917  0.283837  0.743285
7   0.008583  0.418011  0.576375  0.846319  0.036786
8   0.746561  0.941830  0.427376  0.025858  0.878224
9   0.182624  0.384800  0.508343  0.294174  0.464538
10  0.036670  0.735343  0.047704  0.288377  0.177707
11  0.550370  0.403481  0.694171  0.533740  0.398502
12  0.582828  0.480664  0.807208  0.559791  0.289812
13  0.059456  0.987773  0.725639  0.746979  0.850797
14  0.942013  0.526855  0.158705  0.722046  0.953095


In [75]:
print(df.drop([5]))

           A         B         C         D         E
0   0.103812  0.468474  0.859287  0.349166  0.185609
1   0.511680  0.204882  0.263489  0.589505  0.895365
2   0.380236  0.131411  0.945151  0.167400  0.690530
3   0.944711  0.702896  0.546167  0.594436  0.903404
4   0.924199  0.438872  0.904389  0.039238  0.350977
6   0.164734  0.077882  0.465917  0.283837  0.743285
7   0.008583  0.418011  0.576375  0.846319  0.036786
8   0.746561  0.941830  0.427376  0.025858  0.878224
9   0.182624  0.384800  0.508343  0.294174  0.464538
10  0.036670  0.735343  0.047704  0.288377  0.177707
11  0.550370  0.403481  0.694171  0.533740  0.398502
12  0.582828  0.480664  0.807208  0.559791  0.289812
13  0.059456  0.987773  0.725639  0.746979  0.850797
14  0.942013  0.526855  0.158705  0.722046  0.953095


In [76]:
print(df.drop([5,6]))

           A         B         C         D         E
0   0.103812  0.468474  0.859287  0.349166  0.185609
1   0.511680  0.204882  0.263489  0.589505  0.895365
2   0.380236  0.131411  0.945151  0.167400  0.690530
3   0.944711  0.702896  0.546167  0.594436  0.903404
4   0.924199  0.438872  0.904389  0.039238  0.350977
7   0.008583  0.418011  0.576375  0.846319  0.036786
8   0.746561  0.941830  0.427376  0.025858  0.878224
9   0.182624  0.384800  0.508343  0.294174  0.464538
10  0.036670  0.735343  0.047704  0.288377  0.177707
11  0.550370  0.403481  0.694171  0.533740  0.398502
12  0.582828  0.480664  0.807208  0.559791  0.289812
13  0.059456  0.987773  0.725639  0.746979  0.850797
14  0.942013  0.526855  0.158705  0.722046  0.953095


In [77]:
print(df) # it means that origional dataset is not changed

           A         B         C         D         E
0   0.103812  0.468474  0.859287  0.349166  0.185609
1   0.511680  0.204882  0.263489  0.589505  0.895365
2   0.380236  0.131411  0.945151  0.167400  0.690530
3   0.944711  0.702896  0.546167  0.594436  0.903404
4   0.924199  0.438872  0.904389  0.039238  0.350977
5   0.234998  0.951546  0.521000  0.297437  0.679109
6   0.164734  0.077882  0.465917  0.283837  0.743285
7   0.008583  0.418011  0.576375  0.846319  0.036786
8   0.746561  0.941830  0.427376  0.025858  0.878224
9   0.182624  0.384800  0.508343  0.294174  0.464538
10  0.036670  0.735343  0.047704  0.288377  0.177707
11  0.550370  0.403481  0.694171  0.533740  0.398502
12  0.582828  0.480664  0.807208  0.559791  0.289812
13  0.059456  0.987773  0.725639  0.746979  0.850797
14  0.942013  0.526855  0.158705  0.722046  0.953095


In [82]:
df = df.drop(['D',"E"],axis = 1)
df = df.drop([3,5,8,11,14])
print(df)

           A         B         C
0   0.103812  0.468474  0.859287
1   0.511680  0.204882  0.263489
2   0.380236  0.131411  0.945151
4   0.924199  0.438872  0.904389
6   0.164734  0.077882  0.465917
7   0.008583  0.418011  0.576375
9   0.182624  0.384800  0.508343
10  0.036670  0.735343  0.047704
12  0.582828  0.480664  0.807208
13  0.059456  0.987773  0.725639


# reset index

In [90]:
print(df.reset_index())

   index         A         B         C
0      0  0.103812  0.468474  0.859287
1      1  0.511680  0.204882  0.263489
2      2  0.380236  0.131411  0.945151
3      3  0.924199  0.438872  0.904389
4      4  0.164734  0.077882  0.465917
5      5  0.008583  0.418011  0.576375
6      6  0.182624  0.384800  0.508343
7      7  0.036670  0.735343  0.047704
8      8  0.582828  0.480664  0.807208
9      9  0.059456  0.987773  0.725639


In [92]:
df.reset_index(drop=True, inplace = True)
df

A         B         C
0  0.103812  0.468474  0.859287
1  0.511680  0.204882  0.263489
2  0.380236  0.131411  0.945151
3  0.924199  0.438872  0.904389
4  0.164734  0.077882  0.465917
5  0.008583  0.418011  0.576375
6  0.182624  0.384800  0.508343
7  0.036670  0.735343  0.047704
8  0.582828  0.480664  0.807208
9  0.059456  0.987773  0.725639

# ILOC

In [94]:
print(df)

          A         B         C
0  0.103812  0.468474  0.859287
1  0.511680  0.204882  0.263489
2  0.380236  0.131411  0.945151
3  0.924199  0.438872  0.904389
4  0.164734  0.077882  0.465917
5  0.008583  0.418011  0.576375
6  0.182624  0.384800  0.508343
7  0.036670  0.735343  0.047704
8  0.582828  0.480664  0.807208
9  0.059456  0.987773  0.725639


In [96]:
print(df.iloc[[0,4]])

          A         B         C
0  0.103812  0.468474  0.859287
4  0.164734  0.077882  0.465917


In [99]:
df.iloc[[0,1],[0,2]]

A         C
0  0.103812  0.859287
1  0.511680  0.263489

In [100]:
df["C"]= None
print(df)

          A         B     C
0  0.103812  0.468474  None
1  0.511680  0.204882  None
2  0.380236  0.131411  None
3  0.924199  0.438872  None
4  0.164734  0.077882  None
5  0.008583  0.418011  None
6  0.182624  0.384800  None
7  0.036670  0.735343  None
8  0.582828  0.480664  None
9  0.059456  0.987773  None


# dropna()

In [109]:
sh = pd.read_csv("superhero.csv")
print(sh)

       Name        Toy        Born
0  Superman        NaN         NaN
1    Batman  Batmobile  1940-04-25
2  Catwoman        NaN         NaN


In [110]:
print(sh.dropna())

     Name        Toy        Born
1  Batman  Batmobile  1940-04-25


In [111]:
print(sh.dropna(axis = "columns"))

       Name
0  Superman
1    Batman
2  Catwoman


In [112]:
print(sh.dropna(axis = 1))

       Name
0  Superman
1    Batman
2  Catwoman


In [123]:
print(sh.dropna(axis = "rows"))

     Name        Toy        Born
1  Batman  Batmobile  1940-04-25


In [124]:
print(sh.dropna(axis = 0))

     Name        Toy        Born
1  Batman  Batmobile  1940-04-25


In [125]:
print(sh.dropna())

     Name        Toy        Born
1  Batman  Batmobile  1940-04-25


In [126]:
sh.dropna(inplace =True)

In [127]:
sh

Name        Toy        Born
1  Batman  Batmobile  1940-04-25

# DROP DUPLICATE

In [132]:
iceshop = pd.read_csv("iceshop.csv")
print(iceshop)

       Brand Style  Rating
0      Kulfa   Cup     4.0
1      Kulfa   Cup     4.0
2    Praline  Pack     3.5
3      Mango   Cup     4.5
4      Mango   Cup     4.5
5  Chocolate  Pack     4.0


In [135]:
print(iceshop.drop_duplicates())

       Brand Style  Rating
0      Kulfa   Cup     4.0
2    Praline  Pack     3.5
3      Mango   Cup     4.5
5  Chocolate  Pack     4.0


In [137]:
print(iceshop.drop_duplicates(subset =["Brand"])) # remove duplicate from subset

       Brand Style  Rating
0      Kulfa   Cup     4.0
2    Praline  Pack     3.5
3      Mango   Cup     4.5
5  Chocolate  Pack     4.0


In [141]:
print(iceshop.drop_duplicates(subset =["Style"]))

     Brand Style  Rating
0    Kulfa   Cup     4.0
2  Praline  Pack     3.5


In [143]:
iceshop.drop_duplicates(inplace = True)
print(iceshop)

       Brand Style  Rating
0      Kulfa   Cup     4.0
2    Praline  Pack     3.5
3      Mango   Cup     4.5
5  Chocolate  Pack     4.0


In [144]:
iceshop

Brand Style  Rating
0      Kulfa   Cup     4.0
2    Praline  Pack     3.5
3      Mango   Cup     4.5
5  Chocolate  Pack     4.0

# SHAPE

In [146]:
print(iceshop.shape)

(4, 3)


# INFO

In [147]:
iceshop.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 4 entries, 0 to 5
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Brand   4 non-null      object 
 1   Style   4 non-null      object 
 2   Rating  4 non-null      float64
dtypes: float64(1), object(2)
memory usage: 128.0+ bytes
